[2022-07-16 19:00:32,329] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.is_postgres_file_available manual__2022-07-16T19:00:23.099526+00:00 [queued]>
[2022-07-16 19:00:32,343] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.is_postgres_file_available manual__2022-07-16T19:00:23.099526+00:00 [queued]>
[2022-07-16 19:00:32,343] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 19:00:32,343] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-16 19:00:32,343] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 19:00:32,364] {taskinstance.py:1397} INFO - Executing <Task(HttpSensor): is_postgres_file_available> on 2022-07-16 19:00:23.099526+00:00
[2022-07-16 19:00:32,371] {standard_task_runner.py:52} INFO - Started process 868 to run task
[2022-07-16 19:00:32,374] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_files', 'is_postgres_file_available', 'manual__2022-07-16T19:00:23.099526+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/process_files.py', '--cfg-path', '/tmp/tmp5jey6kly', '--error-file', '/tmp/tmpykkmtkjx']
[2022-07-16 19:00:32,374] {standard_task_runner.py:80} INFO - Job 5: Subtask is_postgres_file_available
[2022-07-16 19:00:32,432] {task_command.py:371} INFO - Running <TaskInstance: process_files.is_postgres_file_available manual__2022-07-16T19:00:23.099526+00:00 [running]> on host 98d7be6daedb
[2022-07-16 19:00:32,514] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_files
AIRFLOW_CTX_TASK_ID=is_postgres_file_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-16T19:00:23.099526+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-16T19:00:23.099526+00:00
[2022-07-16 19:00:32,514] {http.py:97} INFO - Poking: world.sql
[2022-07-16 19:00:32,541] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-16 19:00:32,542] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/world.sql
[2022-07-16 19:00:37,812] {http.py:97} INFO - Poking: world.sql
[2022-07-16 19:00:37,820] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-16 19:00:37,821] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/world.sql
[2022-07-16 19:00:42,904] {http.py:97} INFO - Poking: world.sql
[2022-07-16 19:00:42,911] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-16 19:00:42,912] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/world.sql
[2022-07-16 19:00:48,001] {http.py:97} INFO - Poking: world.sql
[2022-07-16 19:00:48,007] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-16 19:00:48,008] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/world.sql
[2022-07-16 19:00:53,095] {http.py:97} INFO - Poking: world.sql
[2022-07-16 19:00:53,101] {base.py:68} INFO - Using connection ID 'http_api' for task execution.
[2022-07-16 19:00:53,102] {http.py:129} INFO - Sending 'GET' to url: http://raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/world.sql
[2022-07-16 19:00:53,187] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 288, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: process_files
[2022-07-16 19:00:53,201] {taskinstance.py:1420} INFO - Immediate failure requested. Marking task as FAILED. dag_id=process_files, task_id=is_postgres_file_available, execution_date=20220716T190023, start_date=20220716T190032, end_date=20220716T190053
[2022-07-16 19:00:53,211] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task is_postgres_file_available (Snap. Time is OUT. DAG id: process_files; 868)
[2022-07-16 19:00:53,246] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-16 19:00:53,286] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
