[2022-07-14 22:49:45,468] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.download manual__2022-07-14T22:47:46.166450+00:00 [queued]>
[2022-07-14 22:49:45,487] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.download manual__2022-07-14T22:47:46.166450+00:00 [queued]>
[2022-07-14 22:49:45,487] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-14 22:49:45,487] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-07-14 22:49:45,487] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-14 22:49:45,510] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): download> on 2022-07-14 22:47:46.166450+00:00
[2022-07-14 22:49:45,519] {standard_task_runner.py:52} INFO - Started process 1621 to run task
[2022-07-14 22:49:45,522] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_files', 'download', 'manual__2022-07-14T22:47:46.166450+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/process_files.py', '--cfg-path', '/tmp/tmpdhxoata_', '--error-file', '/tmp/tmp1me2zvy9']
[2022-07-14 22:49:45,523] {standard_task_runner.py:80} INFO - Job 13: Subtask download
[2022-07-14 22:49:45,603] {task_command.py:371} INFO - Running <TaskInstance: process_files.download manual__2022-07-14T22:47:46.166450+00:00 [running]> on host 4bf3acff5795
[2022-07-14 22:49:45,706] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_files
AIRFLOW_CTX_TASK_ID=download
AIRFLOW_CTX_EXECUTION_DATE=2022-07-14T22:47:46.166450+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-14T22:47:46.166450+00:00
[2022-07-14 22:49:45,781] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_files.py", line 14, in download_file
    outfile.write(indata)
TypeError: write() argument must be str, not Response
[2022-07-14 22:49:45,793] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=process_files, task_id=download, execution_date=20220714T224746, start_date=20220714T224945, end_date=20220714T224945
[2022-07-14 22:49:45,804] {standard_task_runner.py:97} ERROR - Failed to execute job 13 for task download (write() argument must be str, not Response; 1621)
[2022-07-14 22:49:45,855] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-14 22:49:45,903] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
