[2022-07-16 18:44:41,327] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.is_postgres_file_available scheduled__2022-07-15T00:00:00+00:00 [queued]>
[2022-07-16 18:44:41,336] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.is_postgres_file_available scheduled__2022-07-15T00:00:00+00:00 [queued]>
[2022-07-16 18:44:41,336] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 18:44:41,336] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-16 18:44:41,336] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 18:44:41,350] {taskinstance.py:1397} INFO - Executing <Task(HttpSensor): is_postgres_file_available> on 2022-07-15 00:00:00+00:00
[2022-07-16 18:44:41,356] {standard_task_runner.py:52} INFO - Started process 109 to run task
[2022-07-16 18:44:41,358] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_files', 'is_postgres_file_available', 'scheduled__2022-07-15T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/process_files.py', '--cfg-path', '/tmp/tmpfvnfa0as', '--error-file', '/tmp/tmpuslu2255']
[2022-07-16 18:44:41,358] {standard_task_runner.py:80} INFO - Job 3: Subtask is_postgres_file_available
[2022-07-16 18:44:41,414] {task_command.py:371} INFO - Running <TaskInstance: process_files.is_postgres_file_available scheduled__2022-07-15T00:00:00+00:00 [running]> on host 98d7be6daedb
[2022-07-16 18:44:41,489] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_files
AIRFLOW_CTX_TASK_ID=is_postgres_file_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-15T00:00:00+00:00
[2022-07-16 18:44:41,489] {http.py:97} INFO - Poking: world.sql
[2022-07-16 18:44:41,512] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 112, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 103, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 114, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `http_api` isn't defined
[2022-07-16 18:44:41,515] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=process_files, task_id=is_postgres_file_available, execution_date=20220715T000000, start_date=20220716T184441, end_date=20220716T184441
[2022-07-16 18:44:41,525] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task is_postgres_file_available (The conn_id `http_api` isn't defined; 109)
[2022-07-16 18:44:41,569] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-16 18:44:41,614] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
